const express = require('express');
const fs = require('fs');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 3000;
const DB = path.join(__dirname, 'data.json');
app.use(express.json());
app.use(express.static(__dirname));

const seed = {
  students: [{id:'STU001',name:'Sai',password:'1234',department:'AI & Data Science',year:2,semester:3,className:'II-AIDS-A',cgpa:8.6,subjects:[
    {name:'Mathematics',marks:82,attendance:91,assignments:86,internal:80,trend:76},
    {name:'Python',marks:94,attendance:89,assignments:94,internal:90,trend:90},
    {name:'Java',marks:61,attendance:73,assignments:65,internal:64,trend:58},
    {name:'Data Science',marks:88,attendance:86,assignments:89,internal:84,trend:86},
    {name:'Artificial Intelligence',marks:91,attendance:82,assignments:91,internal:88,trend:88}
  ]}],
  teachers:[{id:'FAC001',name:'Professor Kumar',password:'1234',department:'AI & Data Science',classes:['II-AIDS-A'],subjects:['Java','Data Structures']}],
  admins:[{id:'ADM001',name:'Academic Administrator',password:'1234'}],
  assignments:[{id:'ASM001',title:'Java OOP Inheritance Practice',description:'Complete 5 inheritance programming problems and submit your source notes.',subject:'Java',className:'II-AIDS-A',teacherId:'FAC001',maxScore:10,dueDate:'2026-08-20',priority:'High',createdDate:'2026-08-16'}],
  submissions:[], attendance:[], notifications:[]
};
function db(){ if(!fs.existsSync(DB)) fs.writeFileSync(DB,JSON.stringify(seed,null,2)); return JSON.parse(fs.readFileSync(DB)); }
function save(data){ fs.writeFileSync(DB,JSON.stringify(data,null,2)); }
function studentScore(s){ return Math.round(s.subjects.reduce((a,x)=>a+x.marks,0)/s.subjects.length); }
function attendance(s){ return Math.round(s.subjects.reduce((a,x)=>a+x.attendance,0)/s.subjects.length); }
function health(s,d){ const evaluated=d.submissions.filter(x=>x.studentId===s.id&&Number.isFinite(x.score)); const assignment=evaluated.length?evaluated.reduce((a,x)=>a+(x.score/x.maxScore*100),0)/evaluated.length:s.subjects.reduce((a,x)=>a+x.assignments,0)/s.subjects.length; const sub=s.subjects.reduce((a,x)=>a+x.internal,0)/s.subjects.length, trend=s.subjects.reduce((a,x)=>a+x.trend,0)/s.subjects.length; return Math.round(studentScore(s)*.4+attendance(s)*.2+assignment*.2+sub*.1+trend*.1); }
function risk(s){let score=studentScore(s), att=attendance(s); return att<75||score<60?'HIGH RISK':att<85||score<75?'NEEDS ATTENTION':'STABLE';}
function profile(s,d){return {...s,academicScore:studentScore(s),attendance:attendance(s),academicHealth:health(s,d),risk:risk(s)};}
function auth(req,res,next){ const token=req.headers.authorization; if(!token) return res.status(401).json({message:'Login required'}); try{req.user=JSON.parse(Buffer.from(token,'base64').toString());next();}catch{return res.status(401).json({message:'Invalid session'});} }
function requireRole(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({message:'Unauthorized access'});}

app.post('/api/auth/login',(req,res)=>{const {role,id,password}=req.body; const data=db(); const groups={student:data.students,teacher:data.teachers,admin:data.admins}; const found=(groups[role]||[]).find(x=>x.id===id&&x.password===password); if(!found)return res.status(401).json({message:'Invalid ID or password.'}); const user={role,id:found.id,name:found.name}; res.json({token:Buffer.from(JSON.stringify(user)).toString('base64'),user});});
app.get('/api/dashboard/student',auth,requireRole('student'),(req,res)=>{const d=db(),s=d.students.find(x=>x.id===req.user.id);res.json({student:profile(s,d),assignments:d.assignments.filter(a=>a.className===s.className),submissions:d.submissions.filter(x=>x.studentId===s.id)});});
app.get('/api/dashboard/teacher',auth,requireRole('teacher'),(req,res)=>{const d=db(),t=d.teachers.find(x=>x.id===req.user.id),students=d.students.filter(s=>t.classes.includes(s.className)).map(s=>profile(s,d));res.json({teacher:t,students,assignments:d.assignments.filter(a=>a.teacherId===t.id),submissions:d.submissions});});
app.get('/api/dashboard/admin',auth,requireRole('admin'),(req,res)=>{const d=db();res.json({students:d.students.map(s=>profile(s,d)),teachers:d.teachers,assignments:d.assignments});});
app.get('/api/students/:id',auth,requireRole('teacher','admin'),(req,res)=>{const d=db(),s=d.students.find(x=>x.id===req.params.id);if(!s)return res.status(404).json({message:'Student not found'});if(req.user.role==='teacher'){const t=d.teachers.find(x=>x.id===req.user.id);if(!t.classes.includes(s.className))return res.status(403).json({message:'This student is not assigned to your class'});}res.json({student:profile(s,d),submissions:d.submissions.filter(x=>x.studentId===s.id)});});
app.post('/api/assignments',auth,requireRole('teacher'),(req,res)=>{const d=db(),a={id:'ASM'+Date.now(),teacherId:req.user.id,createdDate:new Date().toISOString().slice(0,10),...req.body};if(!a.title||!a.subject||!a.className||!a.dueDate||!(a.maxScore>0))return res.status(400).json({message:'Complete all required assignment fields.'});d.assignments.push(a);d.notifications.push({role:'student',text:`New ${a.subject} assignment: ${a.title}`,date:new Date().toISOString()});save(d);res.status(201).json(a);});
app.put('/api/assignments/:id',auth,requireRole('teacher'),(req,res)=>{const d=db(),a=d.assignments.find(x=>x.id===req.params.id&&x.teacherId===req.user.id);if(!a)return res.status(404).json({message:'Assignment not found'});Object.assign(a,req.body);save(d);res.json(a);});
app.delete('/api/assignments/:id',auth,requireRole('teacher'),(req,res)=>{const d=db(),i=d.assignments.findIndex(x=>x.id===req.params.id&&x.teacherId===req.user.id);if(i<0)return res.status(404).json({message:'Assignment not found'});d.assignments.splice(i,1);save(d);res.status(204).end();});
app.post('/api/assignments/:id/submit',auth,requireRole('student'),(req,res)=>{const d=db(),a=d.assignments.find(x=>x.id===req.params.id),s=d.students.find(x=>x.id===req.user.id);if(!a||a.className!==s.className)return res.status(404).json({message:'Assignment not available'});let sub=d.submissions.find(x=>x.assignmentId===a.id&&x.studentId===s.id);if(!sub){sub={assignmentId:a.id,studentId:s.id};d.submissions.push(sub)}Object.assign(sub,{status:'submitted',comment:req.body.comment||'',fileName:req.body.fileName||'No file attached',submittedDate:new Date().toISOString().slice(0,10),maxScore:a.maxScore});d.notifications.push({role:'teacher',text:`New submission from ${s.name} for ${a.title}`,date:new Date().toISOString()});save(d);res.json(sub);});
app.post('/api/assignments/:id/evaluate/:studentId',auth,requireRole('teacher'),(req,res)=>{const d=db(),a=d.assignments.find(x=>x.id===req.params.id&&x.teacherId===req.user.id),s=d.students.find(x=>x.id===req.params.studentId);if(!a||!s)return res.status(404).json({message:'Assignment or student not found'});const score=Number(req.body.score);if(!Number.isFinite(score)||score<0||score>a.maxScore)return res.status(400).json({message:`Score must be between 0 and ${a.maxScore}.`});let sub=d.submissions.find(x=>x.assignmentId===a.id&&x.studentId===s.id);if(!sub){sub={assignmentId:a.id,studentId:s.id,status:'submitted',submittedDate:new Date().toISOString().slice(0,10),maxScore:a.maxScore};d.submissions.push(sub)}Object.assign(sub,{score,feedback:req.body.feedback||'',evaluatedBy:req.user.id,evaluatedDate:new Date().toISOString().slice(0,10)});const subject=s.subjects.find(x=>x.name===a.subject);if(subject){subject.assignments=Math.round((subject.assignments+score/a.maxScore*100)/2);subject.marks=Math.round((subject.marks+score/a.maxScore*100)/2);subject.trend=Math.min(100,subject.trend+8)}d.notifications.push({role:'student',studentId:s.id,text:`Score updated: ${a.title} — ${score}/${a.maxScore}`,date:new Date().toISOString()});save(d);res.json({submission:sub,student:profile(s,d)});});
app.post('/api/attendance',auth,requireRole('teacher'),(req,res)=>{const d=db(),{className,subject,records}=req.body,t=d.teachers.find(x=>x.id===req.user.id);if(!t.classes.includes(className))return res.status(403).json({message:'Class is not assigned to you'});records.forEach(r=>{const s=d.students.find(x=>x.id===r.studentId&&x.className===className),sub=s?.subjects.find(x=>x.name===subject);if(sub){sub.attendance=Math.round((sub.attendance*20+(r.present?100:0))/21);d.attendance.push({studentId:s.id,subject,present:r.present,date:new Date().toISOString().slice(0,10)})}});save(d);res.json({message:'Attendance saved successfully.'});});
app.get('/api/notifications',auth,(req,res)=>{const d=db();res.json(d.notifications.filter(n=>n.role===req.user.role&&(!n.studentId||n.studentId===req.user.id)).slice(-8).reverse());});
app.post('/api/ai/chat',auth,(req,res)=>{const d=db(),q=(req.body.question||'').toLowerCase();if(req.user.role==='student'){const s=profile(d.students.find(x=>x.id===req.user.id),d),weak=s.subjects.reduce((a,x)=>a.marks<x.marks?a:x);let answer=q.includes('attendance')?`Your overall attendance is ${s.attendance}%. ${weak.name} is lowest at ${weak.attendance}%; attending the next five classes consistently will improve it.`:q.includes('study')||q.includes('subject')?`Prioritize ${weak.name}: it has a ${weak.marks}% score. Schedule three focused practice sessions this week, then maintain Python and AI.`:`Your academic health is ${s.academicHealth}/100. ${weak.name} needs attention, while ${s.subjects.reduce((a,x)=>a.marks>x.marks?a:x).name} is a clear strength.`;return res.json({answer})}const students=d.students.map(s=>profile(s,d)),atRisk=students.filter(s=>s.risk!=='STABLE'),subjects={};students.forEach(s=>s.subjects.forEach(x=>(subjects[x.name]??=[]).push(x.marks)));const lowest=Object.entries(subjects).map(([name,v])=>[name,v.reduce((a,b)=>a+b,0)/v.length]).sort((a,b)=>a[1]-b[1])[0];res.json({answer:q.includes('risk')?`${atRisk.length} student(s) require attention: ${atRisk.map(x=>x.name).join(', ')||'none'}.`:q.includes('attendance')?`${students.filter(x=>x.attendance<75).length} student(s) are below 75% attendance.`:`${lowest[0]} has the lowest current class average (${Math.round(lowest[1])}%). Consider a targeted revision activity.`});});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
app.listen(PORT,()=>console.log(`College Portal running at http://localhost:${PORT}`));
